# tasks for Red Hat Familly
---
- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_selinux.status == 'enabled'

- name: repository installation
  yum:
    name: "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"
    state: present
...
